---

- hosts: all
  become: true
  tasks:

## Ubuntu  
  - name: install apache2 & libapache2-mod-php packages
    apt:
      update_cache: yes 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian", "Ubuntu"]

##CentOS
  - name: Install apache & php packages for CentOS
    dnf:
      update_cache: yes 
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"