---

- hosts: all
  become: true
  tasks:
    - name: APT - Update cache - step 1
      apt:
        update_cache: yes
    - name: APT - Upgrade - step 2
      apt:
        upgrade: 'yes'
    - name: APT - Cleaning - step 3
      apt:
        autoremove: yes
    - name: APT - Cleaning - step 4
      apt:
        autoclean: yes
    